### ISSUE TITLE
google-clock-sync-manager.service failure on Ubuntu 16.04

### ISSUE THREAD

**Issue by psimonazzi** [GoogleCloudPlatform/compute-image-packages#341]
Seems like issue #304 also happens on Ubuntu 16.04 (tested on current image: v20160921).

**Comment by illfelder** [comment]
/cc @OddBloke 

The Ubuntu images haven't yet updated to the (reasonably) new guest environment.

**Comment by zmarano** [comment]
This has been fixed on the latest Ubuntu 16.04 Xenial image, ubuntu-1604-xenial-v20170125

**Comment by ckmaresca** [comment]
Has this been fixed for 14.04 as well?

**Comment by illfelder** [comment]
Yes, as of early March ubuntu 14.04 is updated to include the new Linux guest environment.

**Comment by ckmaresca** [comment]
Is it updated in the repos as well?  Because re-spinning a new image just to update software seems a bit much....

**Comment by ckmaresca** [comment]
That said, this particular machine has the following uname -a `Linux pi-cron-v2-production 4.4.0-78-generic #99~14.04.2-Ubuntu SMP Thu Apr 27 18:49:46 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by illfelder** [comment]
This particular change was a backwards-incompatible version bump where we rewrote the Linux guest environment to fix bugs (like the one you're experiencing) and add improved testing.

The uname you provided is fairly recent, so to better understand the issue you're experiencing, I have a couple things to try:
-   If you have the gcloud CLI installed, can you do a `gcloud compute disks describe` command on your disk and share the value of your "sourceImage" field? (If you use the web interface you can go to the disks page, find your disk name, and check the source image value).
-   What is the output when you run `ps aux | grep python.*google`?

**Comment by ckmaresca** [comment]
I'll run the command, but the source image for this machine was originally a Google-provided Ubuntu 14.04 from that date.  I'm saying this because we create images for use in instance groups out of standard Google images, so the image source will be different. 

All we do is install a web software stack, configure the machine so it connects to GCP CloudSQL (which blew up yesterday, but Enterprise Support has dealt with that...) and push our code to the machine, so the underlying image is exactly the same (with any `apt-get upgrades` that have occurred since the image was created).

**Comment by ckmaresca** [comment]
Yup, as I thought, the `sourceImage` is an internal image we created from one of the standard Ubuntu disks.

The `ps` command returns

```
root      1501  0.0  0.3  48400 13256 ?        Ss   May24   0:03 /usr/bin/python /usr/share/google/google_daemon/manage_accounts.py
root      1990  0.0  0.3  44080 12996 ?        Ss   May24   0:15 /usr/bin/python /usr/share/google/google_daemon/manage_addresses.py
root     15635  0.0  0.3  43696 12540 ?        Ss   19:52   0:00 /usr/bin/python /usr/share/google/google_daemon/manage_clock_sync.py
root     16804  0.0  0.2  48400 10860 ?        S    20:39   0:00 /usr/bin/python /usr/share/google/google_daemon/manage_accounts.py
```
Also, I get a message about updating Cloud SDK, should this be done?

**Comment by ckmaresca** [comment]
I suppose it's possible it's earlier than March....

While I know you'd like to know this for sure, what really interests me is how to update this to current.....

**Comment by ckmaresca** [comment]
Actually, never mind - I just traced some things in our image library - looks like the original source for that image would have been early this year as the image it was generated from in labeled `Feb17`.

So how do we go about updating this?  Thanks.

**Comment by illfelder** [comment]
Thanks for running the commands! In terms of how to update from the old guest environment, our recommended approach is the one-time update to the newest Ubuntu images. Note that changes to the guest environment will be incremental in the foreseeable future, so package updates should work after this one time update. I would highly suggest modifying your instance group to refer to the image family (if it doesn't already) so that you aren't creating new instances from a potentially deprecated image version.

If you want to update packages in an already running VM, I'll try and give some pointers, but please take a snapshot of your disk so you have a backup in case something goes wrong. Also note that Ubuntu images are managed by Canonical, not Google, so there are likely better ways to do this :)

```
sudo su
ps aux | grep python.*google | awk '{print $2}' | xargs kill -9
apt-get purge --auto-remove gce-daemon gce-startup-scripts
apt-get install gce-compute-image-packages
reboot
```

**Comment by ckmaresca** [comment]
Well, that strategy won't work for us as we need a fair amount of stuff running on top of a standard image.  It's a nice idea in theory, but in practice it doesn't actually work unless you have absolutely everything automated.  We'd like to be at that point, but we are not there yet.

Will update the VMs - we keep a library of images for rollback, no issues with 'backup', these are designed to be replaceable, there is no data on these images.

P.S.  You probably want to use `sudo -i` not `sudo su`....

**Comment by illfelder** [comment]
Thanks - I'll update the comment.

/cc @OddBloke - any issues or changes we should make in the upgrade instructions?

**Comment by OddBloke** [comment]
@illfelder @ckmaresca The metadata on the gce-compute-image-packages package should be sufficient to perform the uninstall of the old environment if you just do `apt install gce-compute-image-packages`. But a full purge might be desirable nonetheless.
