### ISSUE TITLE
debian-9 images?

### ISSUE THREAD

**Issue by icco** [GoogleCloudPlatform/compute-image-packages#367]
Is there any plan to start support for debian-9 images?

**Comment by zmarano** [comment]
Debian Stretch is not yet frozen. We will support Debian 9 when it is released as stable and we plan on having an image for early access sometime after it is frozen- which appears to be Feb 5. https://wiki.debian.org/DebianStretch

**Comment by icco** [comment]
Ah, I was kind of hoping there was going to be some easy way for me to run testing (like once 9 becomes stables, I'd want 10).

**Comment by zmarano** [comment]
You can certainly build your own Debian testing images using the open source tools available. We use bootstrap-vz for GCE Debian images: https://github.com/andsens/bootstrap-vz
There is also project FAI which is being talked about as the Debian supported Cloud image builder: http://fai-project.org/

**Comment by icco** [comment]
Yeah, I really like the fact that I can just point my build system at a base of image family that's provided by a trusted source. Was really hoping that I wouldn't have to build and maintain my own images, since I'm already having to do that for one image family.

**Comment by zmarano** [comment]
Yeah I understand that. One issue with Debian testing thus far has been it has been difficult to maintain a stable build because it changes so much over its development cycle (by design I guess). Thus, we haven't committed to maintaining a Debian testing image full time yet. We may do something different in the future however.
