### ISSUE TITLE
Ubuntu trusty missing all daemons

### ISSUE THREAD

**Issue by dovy** [GoogleCloudPlatform/compute-image-packages#418]
How the crap do I get the daemons to properly install? Something happened and I can only access the box if I manually add a public key. The gcloud ssh auth or UI w/ ssh button on the console fail to allow access.

Any help would be appreciated.

**Comment by zmarano** [comment]
Which Ubuntu image are you using? The official Ubuntu GCE images all have the daemon's installed by default. We highly recommend you use these images. Ubuntu maintains its own packages for the software in this repo. The two relevant packages on Trusty are:
gce-compute-image-packages
python-google-compute-engine

**Comment by dovy** [comment]
I did, that's the issue. So I just ran an apt-get on gce-compute-image-packages and got an update. 

So how do I launch the agents?

**Comment by zmarano** [comment]
Its possible you updated from the old packages to the new here. The daemon's launch via upstart as does everything on Trusty. Everything should start correctly on boot. Ubuntu does use different post install scripts from what is published here and they don't automatically start the daemon's in postinst like we do. Normally, this wouldn't be a problem.

Try this:
start google-instance-setup
start google-network-setup
start google-accounts-daemon
start google-clock-skew-daemon
start google-ip-forwarding-daemon

**Comment by dovy** [comment]
```
$ sudo start google-instance-setup
start: Job failed to start
$ start google-network-setup
start: Job failed to start
```

The rest succeeded and I restarted the machine.

I can SSH locally on my machine via gcloud: `gcloud compute --project "redux-framework" ssh --zone "us-central1-b" "redux"` 
But using the ssh interface (Web GUI) yields this: https://cloudup.com/iJZOtOIziUm

The issue is that I have a windows user who tried installing gcloud and has spaces in his name, so I'm trying to get him SSH'd into the gui, with no luck.

Honestly I am a little sad by the Ubuntu image. I've always used Debian Squeeze/Lenny, and decided to give Ubuntu Trusty a try, but these problems are a bit frustrating. If you could assist, I'd appreciate it.

One thing I did do was reinstall the gcloud sdk and used my personal account to authenticate hoping that would resolve the issue, yet to no avail.

**Comment by zmarano** [comment]
I don't think your problems here are with Trusty, Ubuntu, or the daemon's- since you can use gcloud to login these things are all working as expected. One possible reason a user couldn't SSH in is if they don't have the correct IAM permissions to the instance. SSH keys have to be transferred to metadata- if the user in question does not have access to modify the instance they won't be able to SSH in either. Also, user names in Linux can't have spaces. In any case, you may find some more useful answers for these specific problems if you ask your questions in the discussion group: https://groups.google.com/forum/#!forum/gce-discussion

Closing this issue out as there is not an issue with the software in this repository.
