### ISSUE TITLE
Very unhelpful startup traceback if the syslog is unavailable

### ISSUE THREAD

**Issue by the-maldridge** [GoogleCloudPlatform/compute-image-packages#445]
If for some reason the system logging socket is unavailable (i.e. the syslog failed to start, or is not installed) all of the daemons and init tasks provided by this package die with a traceback for a socket error.  The errno returned is 2 (no such file or directory).

It would be nice to catch that exception when the logging is starting up and spit out a print statement that the logging socket is unavailable.  It would also be nice to have an option to gracefully degrade rather than just hitting a hard fault.

**Comment by illfelder** [comment]
The guest environment relies upon syslog to present errors and other logging information to users outside of the VM. If syslog isn't available, catching the exception won't be very helpful since we won't be able to log it anywhere.

That said, the error is likely coming from `logger.py` which each daemon uses. If you'd like to add exception handling there, please make a pull request.

**Comment by the-maldridge** [comment]
That makes sense.  Where catching the exception is very helpful is bootstrapping a new distro which does not have supported packages, logged in to a shell I was able to see the exception and would therefor also see the error that the scripts need syslog to be up.

I will prepare a PR shortly.

**Comment by illfelder** [comment]
Hi, are you still planning to make the PR for this issue?

**Comment by the-maldridge** [comment]
I have a patch, but I'm not really satisfied with how this works.  I'll go ahead and close this issue.
