### ISSUE TITLE
oslogin: json-c's includedir is /usr/include/json-c not /usr/include

### ISSUE THREAD

**Issue by wonderfly** [GoogleCloudPlatform/compute-image-packages#520]
Thus any inclusion of its header files should use `#include <json.h>` as opposed to `#include <json-c/json.h>`, which breaks on systems that rely on `pkg-config` to detect include dir and link dir for libraries.

From json-c upstream: https://github.com/json-c/json-c/blob/master/Makefile.am#L17

This is true even on debian-9.
```
# apt-get install libjson-c-dev
...
# pkg-config --cflags json-c
-I/usr/include/json-c
```

**Comment by Sarsate** [comment]
Does it actually break? In my testing, switching to `#include <json.h>` will break builds that *don't* use `pkg-config`, or don't pass `-I/usr/include/json-c` to the compiler. 

Leaving it as `#include <json-c/json.h>` works for both since /usr/include/ is searched by default. Does this behavior change dramatically for different distros?

It seems worse to have to rely on pkg-config to properly compile.

**Comment by wonderfly** [comment]
The problem amplifies at cross compilation. You are gonna have to use `-I` flags no matter what because you can't use `/usr/include`; it's a path on the host not target. I'd be fine if json-c didn't come with a pkg-config file. But since it does, why don't we follow what it says?

> It seems worse to have to rely on pkg-config to properly compile.

You think it's better to assume that `/usr/include` is always on the search path and that all libraries will install header files under that path? The first might be true for modern compilers but the second can't be.

**Comment by Sarsate** [comment]
Yeah, you're right, we should follow what json-c recommends, and that will leave less room for error.

**Comment by Sarsate** [comment]
Just sent out #524, PTAL!
