### ISSUE TITLE
dependencies not found when apt-get install gce-compute-image-packages

### ISSUE THREAD

**Issue by juanjosv** [GoogleCloudPlatform/compute-image-packages#521]
When i try to update to allow connection throught web interface, as it say the message in: 

https://cloud.google.com/compute/docs/images/configuring-imported-images#install_guest_environment

I write the command "sudo apt-get install gce-compute-image-packages" after updated the system, and cannt install due to dependencies not found:

Connecting to download.oracle.com (download.oracle.com)|173.223.106.73|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-11-21 16:24:36 ERROR 404: Not Found.

download failed
Oracle JDK 6 is NOT installed.
dpkg: error processing package oracle-java6-installer (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 oracle-java6-installer
E: Sub-process /usr/bin/dpkg returned an error code (1)

Any solutions? Where can i fix the url for this?

**Comment by illfelder** [comment]
What image are you trying to install the guest environment on? When I attempt to update the guest environment in a very old Ubuntu 1404 trusty image, everything works without issue.

**Comment by juanjosv** [comment]
Its a ubuntu 16.04, the jdk is already installed with version 1.8.0_151. And the image, which is explained in the url above, is necessary to connect in Google Cloud CE through the web

**Comment by zmarano** [comment]
We don't have a dependency on java- so the errors you are seeing are from previous failed installs of the "oracle-java6-installer" package. If you try to install any package at all you will probably hit that error until you resolve it. I would start by removing the the "oracle-java6-installer" package entirely and go from there. This isn't however an issue with the GCE software, repositories, or Ubuntu specifically.

**Comment by juanjosv** [comment]
@zmarano: Well, thanks, this was the only result with google compute image packages' forum, and i thougth that i could ask here. Btw, it was a dependency of a dependency, And the problem still. Any other forum you recomend?

**Comment by zmarano** [comment]
Usually Stack Overflow will have useful answers for these kinds of things. But you do have a general dependency problem and it stems from an old version of java (which is EOL and therefore perhaps non-existent). Because you are using oracle's repository and not the JDK from Ubuntu, I doubt you will find much use on Ubuntu's forums but its worth a look anyway. You should find a way to remove all the java6 packages to get things back into a useful state. You could also attempt to remove the oracle repositories and see if you get apt back into a happy state. But I'm just guessing at possible problems here.
