### ISSUE TITLE
syslog-ng incompatibility 

### ISSUE THREAD

**Issue by Guidurand** [GoogleCloudPlatform/compute-image-packages#548]
Hi,

Since the PR : https://github.com/GoogleCloudPlatform/compute-image-packages/pull/531 we can't use syslog-ng anymore, indeed the google-compute-engine package has rsyslog as dependancy

I think it will be better to pass the rsyslog as recommend instead a dependancy and check the rsyslog presence in google_config/bin/google_set_hostname

Thanks a lot

**Comment by zmarano** [comment]
Thanks for the issue Guidurand, do you have your own configs for syslog-ng to export logs to the console? One of the reasons we depend on rsyslog is that we ship an [rsyslog config](https://github.com/GoogleCloudPlatform/compute-image-packages/blob/master/google_config/rsyslog/90-google.conf) to make sure there is enough information printed to the serial console for remote debugging. Since Debian ships rsyslog by default, we only ship configs for rsyslog. We can make the package dependency either rsyslog or syslog-ng however.

**Comment by vbatoufflet** [comment]
Hi @zmarano,

I'm not sure that we have handled the forward to the console in our setup. But it should be doable quite easily I guess.

Debian provides a virtual package name [system-log-daemon](https://packages.debian.org/jessie/system-log-daemon) which can be resolved to any Syslog capable software. Using this as dependency could match everyone's needs.

**Comment by zmarano** [comment]
Oh awesome, thanks for that pointer- that makes sense. We'll do that.

**Comment by Guidurand** [comment]
Hi @zmarano 
I've seen you have fix the syslog incompatibility in this commit : https://github.com/GoogleCloudPlatform/compute-image-packages/commit/f3fd94c33a5e10b2f43e9b2037cdfac2945979e9
Thanks a lot !

Do you have an idea when the new package (2.7.5.2 ?) will be available on the official apt repository for jessie and stretch ? 
https://packages.cloud.google.com/apt/dists/google-compute-engine-jessie-stable/main/binary-amd64/Packages

**Comment by zmarano** [comment]
We need some time to test things out but I'll see if I can get it out today or tomorrow.

**Comment by zmarano** [comment]
The updated package has been tested and published. Let us know if you run into any further problems. Thanks for helping solve this problem!

**Comment by Guidurand** [comment]
thanks, that works perfectly
