### ISSUE TITLE
rsyslog.service doesn't nominally work on Arch Linux: may hang up startup + shutdown

### ISSUE THREAD

**Issue by unquietwiki** [GoogleCloudPlatform/compute-image-packages#662]
-  compute-image-packages/google_compute_engine_init/systemd/google-startup-scripts.service
-  compute-image-packages/google_compute_engine_init/systemd/google-shutdown-scripts.service

**Current**

After=local-fs.target network-online.target network.target rsyslog.service systemd-resolved.service

**"Corrected"**

After=local-fs.target network-online.target network.target systemd-resolved.service

**Comment by zmarano** [comment]
We don't support Arch Linux in GCE and this issue is very specific to that distro. The init scripts and packaging scripts provided here are for the Linux distros we fully support as public GCE images. Standard practice here is that any other distro that wants to support a GCE guest package can pull in the source from this repo and either patch it for their own distro or create distro specific packaging in their own code repo to conform with the specifics of that environment.
