### ISSUE TITLE
/sbin/google-dhclient-script is missing on Ubuntu 18.04 in c-i-p v 2.8.13

### ISSUE THREAD

**Issue by kkm000** [GoogleCloudPlatform/compute-image-packages#782]
Hi, just found this project to report this, and noticed #768 also mentions it. The dhclient script `/sbin/google-dhclient-script` is missing from the image. Just verified that `dhclient -v -sf /sbin/foo` still works but yells at me that the script `foo` is missing, but then fortunately seems to fall back to its default scripts, so everything is more or less fine--I haven't noticed any ill effects. My image is from the UEFI Secure Boot Ubuntu-18.04 family, but I noticed it also uses debian_9 as a fallback to "any other debian":
https://github.com/GoogleCloudPlatform/compute-image-packages/blob/d2d59253ad3bd219b2834fa6c2fa5b4d2cce4ecc/packages/python-google-compute-engine/google_compute_engine/compat.py#L51-L54

Unlike Debian 9, 18.04 ditched NetworkManager (good riddance!), but the end result is same, dhclient is invoked with `-sf` pointing to a missing script.

Installed package version:
```
/usr/lib/python3/dist-packages/google_compute_engine-2.8.13.egg-info/PKG-INFO
```
I indeed have this in `/etc/default/instance_configs.cfg`
```
[NetworkInterfaces]
dhclient_script = /sbin/google-dhclient-script
```
Boot disk image provenance:
```
$ gcloud compute disks describe [...]
creationTimestamp: '2019-05-30T13:52:36.464-07:00'
sourceImage: https://www.googleapis.com/compute/v1/projects/gce-uefi-images/global/images/ubuntu-1804-bionic-v20190514
sourceImageId: '39340661374593072'
```
----
On the occasion, if you do not mind, may I ask a question: why does the google_network_daemon watch for metadata changes on secondary NICs, and runs `dhclient -x` followed by `dhclient` on a change, but excludes the primary one? What is the exact case that it is handling?

**Comment by zmarano** [comment]
Ubuntu 18.04 uses netplan instead of NetworkManager (Debian never used NetworkManager by the way).
http://manpages.ubuntu.com/manpages/disco/en/man5/netplan.5.html

The primary NIC has to be configured via DHCP in the base image otherwise we have no way to talk to the metadata server (or anything else). But secondary NIC configuration is done through metadata values as you pointed out and can be changed over the lifec ycle of the instance. We rely on the system's DHCP client to setup the primary NIC in all cases.
