### ISSUE TITLE
User's home directory not being deleted after user's account is deleted from OS-Login

### ISSUE THREAD

**Issue by yuanzhou** [GoogleCloudPlatform/compute-image-packages#817]
Currently I'm managing users/groups via Google Cloud Identity. And I've noticed that if I delete a user from the Google Admin Console, the user's os-login will be disabled. But since this user has logged into the VM instances, the user's home directory is still on the VMs. And I had to manually delete that Linux user account to remove it from the whole system. 

I tried to delete the user account and home directory but got this:

````
[root@midas-hpc-login1 home]# userdel -r demo_user_midasnetwork_us
userdel: cannot remove entry 'demo_user_midasnetwork_us' from /etc/passwd
````
Apparently the user won't be in `/etc/passwd` . So I just manually removed the user's home directory using 
````
[root@midas-hpc-login1 home]# rm -rf demo_user_midasnetwork_us/
````

Is what I did above the correct procedure?

And I looked at the [`gcloud compute os-login remove-profile`](https://cloud.google.com/sdk/gcloud/reference/compute/os-login/remove-profile), but couldn't get this work.

**Comment by hopkiw** [comment]
Hi @yuanzhou - this behavior is by design, we default to preserving user accounts and therefore home directories. If you'd like users who are deprovisioned or have their access removed in OS Login (or whose last SSH key is deleted, if not using OS Login) to be removed, you can set the `deprovision_remove` option in the INI configuration file, see documentation [here](https://github.com/GoogleCloudPlatform/compute-image-packages/tree/master/packages/python-google-compute-engine#configuration)

**Comment by yuanzhou** [comment]
@hopkiw Thanks for the information.
