### ISSUE TITLE
Re-enable boto setup on python3 but remove plugin line

### ISSUE THREAD

**Issue by zmarano** [GoogleCloudPlatform/compute-image-packages#820]
For standalone gsutil installs (not the included gcloud installed gsutil) the boto config file is needed but without the problematic plugin which breaks on python3 systems. We can instead just write the rest of the boto config file and drop the plugin.

**Comment by houglum** [comment]
For context, I found this today running some release tests -- tests were failing because they expected service account credentials to "just work", but no credentials were being supplied.

It looks like https://github.com/GoogleCloudPlatform/compute-image-packages/pull/764 is the change that resulted in no longer writing the /etc/boto.cfg file on some GCE images (if Python 3 was used to run the instance config code) -- this doesn't necessarily correspond to the default Python version on the machine, or the one being used to run gsutil; when running on a Debian 9 image today, I see `python` loads Py 2.7.13, but there's no file at /etc/boto.cfg.  It looks like Debian 9 is the only affected image, as far as I can tell.

This resulted in standalone installations of gsutil (i.e. installed separately via tarball or `pip`) not working out-of-the-box on GCE VMs as they used to.  While most users *probably* just use the gcloud-packaged installation of gsutil that comes with our VMs, there are inevitably users that need to use a separate installation of gsutil and expect GCE service account auth to still "just work".

As mentioned above, gsutil doesn't need the `[Plugin]` section of the config file, but it **does** need the rest of the content to be available in /etc/boto.cfg.
