### ISSUE TITLE
Very slow Docker builds when oslogin is enabled

### ISSUE THREAD

**Issue by martinraison** [GoogleCloudPlatform/compute-image-packages#824]
Hi, I observed this surprising behavior today:

1) log into a machine with OS Login enabled

2) try to build a docker image that uses a non-root user, for example with the following instructions in the Dockerfile:

```
FROM ubuntu:16.04

RUN adduser --disabled-password --gecos '' --shell /bin/bash user
USER user

[...install programs, move files around, do some regular Dockerfile stuff...]
```

3) the resulting build is *extremely* slow

Using `strace` on the host's `dockerd` during the build, I saw many syscalls trying to access files *inside the container* (I'm not familiar at all with how Docker/OverlayFS handle this). I was able to see that many of those file accesses trigger a request to http://metadata.google.internal/computeMetadata/v1/oslogin/users?uid=1000, which returns a 404 Not Found. This is likely because the OS Login system doesn't know anything about uid 1000, since it's a user created inside of the Docker container.

By using the default "root" user in the container instead of switching to a custom user, the problem disappeared.

I can't really decide if this is a more of an OS Login or Docker issue, but I thought you should be aware of this.

**Comment by hopkiw** [comment]
So what seems to be happening here is that you're creating a user within the container that is not known to the VM outside the container. During the build, commands run as this user result in some files being created with the owner set to its UID (default 1000). Separately, some docker processes running outside of the container look at these files and as a result try to look up what name that UID should resolve to. Since it is not a local user on the VM, it tries a lookup to the OS Login service which also indicates this is an unknown user. If you do this a lot in a short time, you can be throttled by the OS Login service, resulting in an overall slowdown for your build process.

Overall this is normal behavior for user lookups and for docker builds, so it isn't a strictly speaking a bug. It's a side effect of the fact that you have a user which only exists inside the container, but whose files are being looked at from outside of the container. Even without OS Login, there would be a lot of these failed UID lookups, just without any slowdown side effect since they'd only need to check the local passwd database.

In the future we are looking at improving the local caching layer for OS Login to also cache missed lookups, which will resolve this kind of issue. In the meantime, there may be some workarounds. You could create a user on your VM with the same UID prior to running docker build, optionally removing it post-build. You could move the `USER` verb to the end of the dockerfile (and maybe do some retroactive `chown` if needed). Or you could restrict yourself to only building containers which have embedded users on a non-OS Login VM.

**Comment by martinraison** [comment]
Thanks a lot @hopkiw for the detailed reply ! There are a few workarounds as you mentioned. However I agree that caching missed lookups would be quite nice.
