### ISSUE TITLE
system hangs on name resolution failure (startup or shutdown)

### ISSUE THREAD

**Issue by rjschwei** [GoogleCloudPlatform/compute-image-packages#862]
Upon shutdown script_manager attemptes to retrieve data from the metadata server via the call chain
ScriptManager.RunScripts() -> retriever.GetScripts() -> watcher.GetMetadata()

While MetadataWatcher.GetMetadata() has arguments to avoid a forever loop in MetadataWatcher._HandleMetadataUpdate() by setting the "retry" argument to false this control option is not available in retriever.GetScripts(). Therefore it is not possible for the startup or shutdown sequence to succeed if name resolution fails.

Potential options for addressing the issue:
1.) Add the control options from MetadataWatcher.GetMetadata() to higher level implementations that call this code.
  + This would allow the ScriptManager.RunScripts() code to avoid an infinite loop as retriever.GetScripts(retry=False) could be used

2.) Add a retry counter to MetadataWatcher._HandleMetadataUpdate()
  + Have a set number of retries, maybe 50 to allow a potential transient network access issue to clear. This would introduce a delay in the case that showed this problem, but a system with persistent name resolution problems would still start or shutdown

3.) Explicitly ignore name resolution errors in MetadataWatcher._HandleMetadataUpdate()
  + This implies to abandon the wait loop when no name resolution is possible. However this also implies that if the issue is transient any data that may be important will not be considered.

IMHO 1 should be the preferred implementation approach but I didn't want to go down that path if there is not general consensus.

Please let me know and I'll be happy to provide a PR.

**Comment by BongoEADGC6** [comment]
I've confirmed the newest version including fix #864 works with shutting down. Was able to build an image in Virtualbox via Packer without any intervention. This can be closed now.

**Comment by hopkiw** [comment]
Thanks for the report @BongoEADGC6 

Also FYI: if you want to bypass shutdown scripts you can disable them with the instance_configs.cfg file or by `systemctl disable google-shutdown-scripts.service`, either one.

**Comment by illfelder** [comment]
Reopening this since we are reverting the pull request.

As part of the instance initialization process, there is a non-deterministic amount of time before the instance will have access to the metadata server. Setting a retry limit may prevent startup scripts from executing, leaving the machine in an undefined (potentially broken) state. It is important that we do not have a retry limit for waiting for metadata during instance setup or before executing startup script. In a followup pull request, we can re-introduce the retry limits, setup functionality should not have limits by default.
